M48
; DRILL file {KiCad 9.0.6} date 2026-03-29T00:05:21+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-29T00:05:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X4.3882Y-2.9921
X4.5882Y-2.9521
X4.5882Y-3.0321
T2
X4.0291Y-2.615
X4.0291Y-3.0874
M30
